apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-cronjob
  namespace: backend-namespace
  labels:
    app.kubernetes.io/name: backup
    app.kubernetes.io/component: cronjob
spec:
  schedule: "0 */3 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      template:
        metadata:
          labels:
            app: backup
            app.kubernetes.io/name: backup
        spec:
          restartPolicy: OnFailure
          containers:
          - name: backup
            image: docker.io/rafaelmao/backup:latest
            imagePullPolicy: Always
            env:
            - name: MY_DATABASE_DRIVER
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MY_DATABASE_DRIVER
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_PORT
            - name: DB_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_USER_NAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_PASSWORD
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_DEFAULT_REGION
            # RECURSOS MÍNIMOS
            resources:
              requests:
                memory: "64Mi"
                cpu: "50m"
              limits:
                memory: "128Mi"
                cpu: "200m"
