apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: backend-namespace
data:
  MY_DATABASE_DRIVER: "postgres"  # Cambia según el driver: mysql, postgres, mongo
  DB_HOST: "postgres-service"  # Nombre del servicio de la DB en K8s
  DB_NAME: "database"
  DB_PORT: "5432"