apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-cronjob
  namespace: backend-namespace
spec:
  schedule: "0 */3 * * *"  # Cada 3 horas
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: docker.io/rafaelmao/backup:latest
            env:
            - name: MY_DATABASE_DRIVER
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MY_DATABASE_DRIVER
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_PORT
            - name: DB_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_USER_NAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_PASSWORD
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_SECRET_ACCESS_KEY
          restartPolicy: OnFailure