apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: backend-namespace
type: Opaque
data:
  DB_USER_NAME: YWRtaW4=  # base64 de 'admin'
  DB_PASSWORD: YWRtaW4xMjM=  # base64 de 'admin123'