apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: backend-namespace
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: secret
type: Opaque
data:
  # Base64 encoded values
  # echo -n 'admin' | base64 = YWRtaW4=
  # echo -n 'admin123' | base64 = YWRtaW4xMjM=
  DB_USER_NAME: YWRtaW4=
  DB_PASSWORD: YWRtaW4xMjM=
