name: Deploy to GKE

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

env:
  PROJECT_ID: project-762c7709-7568-49f1-b91  # Reemplaza con tu Project ID de GCP
  GKE_CLUSTER: codigo-rafael  # Reemplaza con el nombre de tu cluster GKE
  GKE_ZONE: us-central1  # Reemplaza con tu zona

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: projects/455355438110/locations/global/workloadIdentityPools/github-pool/providers/github-provider
        service_account: github-actions-sa@project-762c7709-7568-49f1-b91.iam.gserviceaccount.com

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Install gke-gcloud-auth-plugin
      run: gcloud components install gke-gcloud-auth-plugin

    - name: Get GKE credentials
      run: gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID

    - name: Build and push backend image
      run: |
        docker build -t docker.io/rafaelmao/node-codigo-rafael:latest .
        docker push docker.io/rafaelmao/node-codigo-rafael:latest

    - name: Build and push backup image
      run: |
        docker build -f Dockerfile.backup -t docker.io/rafaelmao/backup:latest .
        docker push docker.io/rafaelmao/backup:latest

    - name: Deploy to GKE
      run: |
        kubectl apply -f namespace.yaml
        kubectl create secret generic aws-secret --from-literal=AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} --from-literal=AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} -n backend-namespace
        kubectl apply -f configmap.yaml
        kubectl apply -f secret.yaml
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        kubectl apply -f cronjob.yaml
        kubectl apply -f deployment-postgres.yaml
        kubectl apply -f service-postgres.yaml
        kubectl apply -f deployment-mysql.yaml
        kubectl apply -f service-mysql.yaml
        kubectl apply -f deployment-mongo.yaml
        kubectl apply -f service-mongo.yaml
        # Esperar a que las bases de datos estén listas
        kubectl wait --for=condition=ready pod -l app=postgres -n backend-namespace --timeout=120s
        kubectl wait --for=condition=ready pod -l app=mysql -n backend-namespace --timeout=120s
        kubectl wait --for=condition=ready pod -l app=mongo -n backend-namespace --timeout=120s